# [START runtime]
runtime: python27
api_version: 1
threadsafe: true
# [END runtime]
handlers:
- url: /(.*\.(js|map|css|png))$
  static_files: dist/\1
  upload: dist/.*\.(js|map|css|png)$

- url: .*
  static_files: dist/index.html
  upload: dist/index.html

skip_files:
- ^(?!dist)  # Skip any files not in the dist folder
